name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: nse-mcp-tools  # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.12'              # set this to the Python version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.8.0"

      - name: Install dependencies
        run: uv sync

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
